server:
  port: 20000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      #配置gateway的请求路由
      routes:
        #当前的配置是路由给学生微服务
        - id: student
          uri: lb://web-student
          predicates:
            - Path=/stu/**
          #filters:
        - id: teacher
          uri: lb://web-teacher
          predicates:
            - Path=/tea/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

